name: 🐛 Bug
description: Report an issue to help improve the project.
title: '⚒ <Description>'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
       ## New to the Project? 
       Check out the getting started guide: https://bit.ly/rr-gettingStarted

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browser are you seeing the problem on ?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Brave
        - Kiwi (Android)
    validations:
      required: false
