name: 💡 Feature Request
description: Have a new idea/feature for this project? Please suggest!
title: '💡 [FEATURE] <description>'
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots if applicable
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## New to the Project? 
        Check out the getting started guide: https://bit.ly/rr-gettingStarted
    validations: 
      required:true
